package ats.rpg.db.hsql;

import java.sql.*;

import ats.rpg.db.dao.InventorySlotDao;
import ats.rpg.db.dao.ItemDao;
import ats.rpg.entities.InventorySlot;
import ats.rpg.entities.Item;
import ats.rpg.util.ItemType;


public class HsqlItemDao extends HsqlDaoBase<Item> implements ItemDao {

	
	public HsqlItemDao(HsqlUnitOfWork uow) {
		super(uow);
	}

	@Override
	public void setInventorySlots(Item item, InventorySlotDao dao) {
		item.setInventorySlots(dao.getInventorySlotsByItemId(item.getId()));
		for(InventorySlot i : item.getInventorySlots()){
			i.setItem(item);
		}
	}
	
	@Override
	public void drop() {
		try {
			drop.execute();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	@Override
	protected String getTableName() {
		return "Item";
	}

	@Override
	protected String getCreateQuery() {
		return "CREATE TABLE Item("
				+ "id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 0),"
				+ "name VARCHAR(50) NOT NULL,"
				+ "type VARCHAR(50) NOT NULL,"
				+ "price INT,"
				+ "damage INT,"
				+ "defense INT,"
				+ "MPbonus INT,"
				+ "UNIQUE(name,type)"
				+ ")";
	}

	@Override
	protected Item build(ResultSet rs) throws SQLException {
		Item i = new Item();
			i.setId(rs.getLong("id"));
			i.setName(rs.getString("name"));
			i.setType(ItemType.valueOf(rs.getString("type")));
			i.setPrice(rs.getInt("price"));
			i.setDamage(rs.getInt("damage"));
			i.setDefense(rs.getInt("defense"));
			i.setMpbonus(rs.getInt("MPbonus"));
		return i;
	}

	@Override
	protected String getInsertQuery() {
		return "insert into Item(name,type,price,damage,defense,MPbonus) "
				+ "values (?,?,?,?,?,?)";
	}

	@Override
	protected void setInsertQuery(Item ent) throws SQLException {
		insert.setString(1, ent.getName());			// Not null
		insert.setString(2, ent.getType());			// Not null
		insert.setInt(3, ent.getPrice());
		insert.setInt(4, ent.getDamage());
		insert.setInt(5, ent.getDefense());
		insert.setInt(6, ent.getMpBonus());
	}

	@Override
	protected String getUpdateQuery() {
		return "update Item set"
				+ "(name,type,price,damage,defense,MPbonus)=(?,?,?,?,?,?)"
				+ "where id=?";
	}

	@Override
	protected void setUpdateQuery(Item ent) throws SQLException {
		update.setString(1, ent.getName());
		update.setString(2, ent.getType());
		update.setInt(3, ent.getPrice());
		update.setInt(4, ent.getDamage());
		update.setInt(5, ent.getDefense());
		update.setInt(6, ent.getMpBonus());
		update.setLong(7, ent.getId());
	}
	
}